### ISSUE TITLE
[TimexExpression] TimexRangeResolver.Evalute misevaluates Sunday (XXXX-WXX-7)

### ISSUE THREAD

**Issue by JonathanFingold** [Microsoft/Recognizers-Text#688]
The following code resolves Sunday to Monday, but resolves Saturday and Monday as expected:

```csharp
var constraints = new[]
{
    TimexCreator.NextWeeksFromToday(2),
    TimexCreator.Evening
};
List<TimexProperty> resolutions = null;
try
{
    resolutions = TimexRangeResolver.Evaluate(candidates, constraints);
}
catch
{
    return null;
}
```

The constraint is being passed in as a LUIS entity, so it is coming in as "XXXX-WXX-7" for Sunday, and as "XXXX-WXX-1" or "XXXX-WXX-6" for Monday or Saturday, respectively.

So running this code today (Tu 7/3) with a candidate of "XXXX-WXX-7" results in { "2018-07-09T16" and "2018-07-16T16" }, both of which are Mondays.

**Comment by johnataylor** [comment]
This looks OK in the C# implementation - I checked with the date mentioned in the issue and with today.

**Comment by JonathanFingold** [comment]
@johnataylor Perhaps the issue got fixed in the last couple months? I'll open a new issue if I run across one. Feel free to close.

**Comment by johnataylor** [comment]
@JonathanFingold  I just tested the JavaScript too - it looks good. Took me a few minutes to get the JavaScript working, however, because the names follow the JavaScript conventions. Desperately need the sample. Did you see I added a TIMEX sample for C# - just a simple console app that runs through some of the APIs. I need to do the same for JavaScript.

Anyhow I'll close this one now.

**Comment by glennmusa** [comment]
This still occurs in the .NET Resolver. Proposed a change here: [https://github.com/Microsoft/Recognizers-Text/pull/1537](https://github.com/Microsoft/Recognizers-Text/pull/1537)

**Comment by tellarin** [comment]
@glennmusa Thanks for double-checking and the fix PR.
